# Generated by Django 4.2.2 on 2023-06-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_subject_specialization_delete_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tema')),
                ('last_name', models.CharField(max_length=50, verbose_name='Tema')),
                ('birthday', models.DateField(verbose_name='Especialidad')),
                ('mail', models.CharField(max_length=50, verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['last_name'],
            },
        ),
    ]
