# Generated by Django 4.2.2 on 2023-06-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_subject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='especialidades', verbose_name='Imagen'),
        ),
    ]
