# Generated by Django 4.2.2 on 2023-06-28 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_specialization_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('idNote', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='Tema')),
                ('written_in', models.DateField(verbose_name='Fecha de creación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='asignaturas', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.specialization', verbose_name='Especialidad')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'apunte',
                'verbose_name_plural': 'apuntes',
                'ordering': ['idNote'],
            },
        ),
    ]
